project:
  title: "MB4 test" # Browser tab title
  type: datapage
  output-dir: docs

website:
  navbar:
    logo: images/logo.png # logo on the navigation bar

format:
  datapage-html:
    theme: theme.scss

execute: 
  echo: false # don't show code
  message: false # don't show messages
  warning: false # don't show warnings
  error: false # don't show errors

redivis:
  user: candice_koolhaas001 # changed from datapages
  dataset: test_mb4 # changed from Many Babies 1
  table: clean_data # changed from 02_validated_output
